#!/bin/bash

perl -p -i -e 's/(__version__ = .*\d+\.\d+\.)(\d+)(.*)/$1 . ($2 + 1) . $3/e' pysonos/__init__.py
git commit -m "Version $(perl -n -e 'print "$1\n" if /__version__ = "(.*)"/' pysonos/__init__.py)" pysonos/__init__.py
