---
name: pysonos

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pysonos-Check-Jobs-Py_3-9:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint with flake8 and pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 pysonos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        pylint pysonos
    - name: Test with pytest
      run: |
        pytest --cov-config .coveragerc --cov pysonos .
    - name: Test formatting with Black
      run: |
        black --check pysonos tests

  pysonos-Check-Jobs-Py_3-8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint with flake8 and pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 pysonos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        pylint pysonos
    - name: Test with pytest
      run: |
        pytest --cov-config .coveragerc --cov pysonos .
    - name: Test formatting with Black
      run: |
        black --check pysonos tests
